eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8760
spring:
  application:
    name: service-job
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: test
      name: job
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.8.128
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
